//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercadoPagoWEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaDigital
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaDigital()
        {
            this.MovimientoCuenta = new HashSet<MovimientoCuenta>();
            this.MovimientoCuenta1 = new HashSet<MovimientoCuenta>();
        }
    
        public int id_cuenta { get; set; }
        public int id_usuario { get; set; }
        public string cvu { get; set; }
        public string alias { get; set; }
        public Nullable<decimal> saldo_actual { get; set; }
        public string moneda { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoCuenta> MovimientoCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoCuenta> MovimientoCuenta1 { get; set; }
    }
}
