//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercadoPagoWEB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MercadoPagoDBEntities1 : DbContext
    {
        public MercadoPagoDBEntities1()
            : base("name=MercadoPagoDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CuentaBancaria> CuentaBancaria { get; set; }
        public virtual DbSet<CuentaDigital> CuentaDigital { get; set; }
        public virtual DbSet<MetodoPago> MetodoPago { get; set; }
        public virtual DbSet<MovimientoCuenta> MovimientoCuenta { get; set; }
        public virtual DbSet<Transaccion> Transaccion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Vista_SaldosContacto> Vista_SaldosContacto { get; set; }
        public virtual DbSet<Vista_UsuariosVerificados> Vista_UsuariosVerificados { get; set; }
    
        public virtual int SP_ActualizarEstadoKYC(Nullable<int> id_usuario, string nuevo_estado)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var nuevo_estadoParameter = nuevo_estado != null ?
                new ObjectParameter("nuevo_estado", nuevo_estado) :
                new ObjectParameter("nuevo_estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarEstadoKYC", id_usuarioParameter, nuevo_estadoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_RealizarTransferencia(Nullable<int> id_origen, Nullable<int> id_destino, Nullable<decimal> monto, string descripcion)
        {
            var id_origenParameter = id_origen.HasValue ?
                new ObjectParameter("id_origen", id_origen) :
                new ObjectParameter("id_origen", typeof(int));
    
            var id_destinoParameter = id_destino.HasValue ?
                new ObjectParameter("id_destino", id_destino) :
                new ObjectParameter("id_destino", typeof(int));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("monto", monto) :
                new ObjectParameter("monto", typeof(decimal));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_RealizarTransferencia", id_origenParameter, id_destinoParameter, montoParameter, descripcionParameter);
        }
    }
}
