//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercadoPagoWEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoCuenta
    {
        public int id_movimiento { get; set; }
        public int id_transaccion { get; set; }
        public Nullable<int> id_cuenta_origen { get; set; }
        public Nullable<int> id_cuenta_destino { get; set; }
        public Nullable<int> id_metodo_pago_vinculado { get; set; }
        public decimal monto_afectado { get; set; }
    
        public virtual CuentaDigital CuentaDigital { get; set; }
        public virtual CuentaDigital CuentaDigital1 { get; set; }
        public virtual MetodoPago MetodoPago { get; set; }
        public virtual Transaccion Transaccion { get; set; }
    }
}
