//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercadoPagoWEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaccion()
        {
            this.MovimientoCuenta = new HashSet<MovimientoCuenta>();
        }
    
        public int id_transaccion { get; set; }
        public decimal monto { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public string tipo_transaccion { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> tarifa_comision { get; set; }
        public string referencia_externa { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoCuenta> MovimientoCuenta { get; set; }
    }
}
