//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercadoPagoWEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista_SaldosContacto
    {
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string email { get; set; }
        public string cvu { get; set; }
        public Nullable<decimal> saldo_actual { get; set; }
        public string moneda { get; set; }
    }
}
